### ISSUE TITLE
Program crashes when first character in a .mcfunction file is a "#"

### ISSUE THREAD

**Issue by PyroSweets** [IoeCmcomc/MCDatapacker#6]
**What:** When starting off a .mcfunction file with a comment, the program freezes and crashes. This is a bit annoying, since every function file must now have some random command before I can annotate my code.
**Where:** Any .mcfunction file in the datapack function folder. I haven't tested it in any other space.
**How to replicate**: Create a new .mcfunction file and type a # as the first code character

**Comment by IoeCmcomc** [comment]
Thanks for reporting. This error affects all text files, not only .mcfuncion files. I fixed this error four months ago (333506a). It should behave normally in the next release. As for now, you can work around this bug by leaving the first line empty.
