### ISSUE TITLE
Bug with saving / loading datapacks

### ISSUE THREAD

**Issue by Cursdd** [IoeCmcomc/MCDatapacker#9]
Sometimes when I close a datapck, the contents of one file will overwrite the contents of either all the others in the same namespace, or everything in the datapack. I don't know how to replicate this though

**Comment by IoeCmcomc** [comment]
I was able to replicate this. Basically, when the program save all files (i.e Ctrl+Shift+S), the content of _the currently editing file_ is saved into _all opening files_.
Sorry for any damage this bug made to your files. You can work around this issue by _saving files manually_ before closing datapacks.

**Comment by Cursdd** [comment]
Does the same thing happen when saving before closing the app (the prompt)?

**Comment by IoeCmcomc** [comment]
Unfortunately, yes.

**Comment by IoeCmcomc** [comment]
Fixed in ed4d403654b1f540ab8ab0d302053abcc1dbf582.
